### ISSUE TITLE
Crashes apon entering edit mode

### ISSUE THREAD

**Issue by iRetr0x** [BeamNG/Blender-JBeam-Editor#1]
I was very excited to check out the jbeam editor and no matter what jbeam i use or what the circumstances are, blender crashes apon entering edit mode??

**Comment by angelo234** [comment]
Hmm what Blender version do you have? This addon only supports the latest version of Blender (3.6.x)

**Comment by iRetr0x** [comment]
Ah I see now that I didn't read, I apologize for the inconvenience. That is exactly my issue and updating blender solved the issue. Thank you.
