### ISSUE TITLE
Jbeam and visual mesh are not the same

### ISSUE THREAD

**Issue by TheM0dMan** [BeamNG/Blender-JBeam-Editor#15]
<img width="337" alt="image" src="https://github.com/BeamNG/Blender-JBeam-Editor/assets/154769000/cead524e-060a-4640-b00c-add0577781f4">

When I move the jbeam the visual mesh does not move with it, and I can also move the visual mesh separately from the jbeam.

Maybe I need to start a new blender project or something for the updates to work?

**Comment by TheM0dMan** [comment]
I am in blender 4.0 and the jbeam editor is on the latest version

**Comment by angelo234** [comment]
Yes please start a new project as projects that you used an older version of the plugin with aren't compatible with new plugin versions.

**Comment by TheM0dMan** [comment]
#

> Yes please start a new project as projects that use an older version of the plugin aren't compatible with new plugin versions.

Thank you
