### ISSUE TITLE
Unable to find the export location of jbeam file

### ISSUE THREAD

**Issue by Hapyhusky** [BeamNG/Blender-JBeam-Editor#16]
I've seen a few youtube video on this addon, they all have "jbeam file" or "jbeam" when exporting, but mine says "export selected jbeams(s)". And I can't find my file anywhere, and when I import the original file again (located in a folder on desktop), no changes were saved.
![Screenshot 2024-03-29 122515](https://github.com/BeamNG/Blender-JBeam-Editor/assets/165339667/7d7e0860-439e-4b2d-a51d-0a03162b5bfd)

**Comment by angelo234** [comment]
So in this version of the plugin, exporting is done on the JBeam file imported. Do you get any error messages in the Blender console (Window > Toggle System Console)?

**Comment by Hapyhusky** [comment]
> So in this version of the plugin, exporting is done on the JBeam file imported. Do you get any error messages in the Blender console (Window > Toggle System Console)?

It says this: 
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/165339667/08610563-b14d-492f-bbf9-aaca0bf6c303)

**Comment by angelo234** [comment]
I see you are using Blender 3.3. You need to update to the latest Blender version for the plugin to work.

**Comment by Hapyhusky** [comment]
> I see you are using Blender 3.3. You need to update to the latest Blender version for the plugin to work.

I checked the website but it says 3.3, I'll have another look

**Comment by Hapyhusky** [comment]
Updated, thanks.
