### ISSUE TITLE
Where is files being exported? / Is it possible to export as a new file?

### ISSUE THREAD

**Issue by ishikawa180** [BeamNG/Blender-JBeam-Editor#17]
Hello! I was trying to make it work for about 3 hours now and i still cant find where it exports the files. I tried searching all my pc but i found nothing.

https://github.com/BeamNG/Blender-JBeam-Editor/assets/116607391/d3fe191c-7551-460d-a572-a2307df4dc44

![Screenshot 2024-05-08 090950](https://github.com/BeamNG/Blender-JBeam-Editor/assets/116607391/63db9820-c1a7-4f2b-8464-5268c6bdbdf3)
![Screenshot 2024-05-08 090734](https://github.com/BeamNG/Blender-JBeam-Editor/assets/116607391/bf4fd050-a8d7-4e5f-8753-93f9f0f1758a)

**Comment by ishikawa180** [comment]
blender 4.1.1 freshly reinstalled with last version of this addon

**Comment by angelo234** [comment]
It gets exported to the file you imported

**Comment by ishikawa180** [comment]
oh

**Comment by angelo234** [comment]
Sorry for the trouble, maybe I should make it more clear in the export message that it exports to that file

**Comment by ishikawa180** [comment]
thank you! it also would be amazing if you could add the entire path to file so its easier to understand where the file is located, because when i imported another jbeam it seems that the original jbeam is now overwritten by the new one, idk maybe im tweaking, but anyway, is there a way to change the file without remaking the entire mesh? id like to reexport it as new file so im sure its the correct iteration

**Comment by ishikawa180** [comment]
sorry to disturb you again

**Comment by angelo234** [comment]
Yeah I can add the option to export to a new file.

**Comment by ishikawa180** [comment]
definitely do! thank you, cant wait for the next update <3
