### ISSUE TITLE
JBEAM not being exported to the game

### ISSUE THREAD

**Issue by cookie-21** [BeamNG/Blender-JBeam-Editor#21]
After editing the JBEAM position with the Blender plugin, and then exporting it, the JBEAM structure doesn't change in game at all.

Namely I'm making a side exit exhaust, and the final exhaust node is still where it was before, even after I exported it.

When I import the same file again, it's just like before, nothing changed.

**Comment by angelo234** [comment]
What version of Blender are you on?

**Comment by Fox-GAMING** [comment]
The same thing happens to me, Blender 4.1.

**Comment by Fox-GAMING** [comment]
It almost seems like it removes the ending brackets from edited nodes.

**Comment by angelo234** [comment]
Try removing the plugin and installing the new version again. And run Blender as an administrator.

**Comment by Fox-GAMING** [comment]
> Try removing the plugin and installing the new version again. And run Blender as an administrator.

Thanks, that worked for me.
