### ISSUE TITLE
JBeam parts are blank.

### ISSUE THREAD

**Issue by AlexEL204** [BeamNG/Blender-JBeam-Editor#23]
After choosing a .jbeam file, and a part to import. The object in the Blender scene has:
- No geometry
- Nor UV Map

The console says 
> Done importing JBeam.

and it still recognizes when there's a JBeam object in the scene, avoiding duplicates.

**Comment by angelo234** [comment]
Sorry I didn't see your issue previously, umm any errors in the console and do you mind sharing the JBeam file (you can send it privately to my email if you wish: amatteo@beamng.gmbh)

**Comment by AlexEL204** [comment]
**Update**:
When some specific .jbeam files are imported, only the "Hitbox" things are imported.

**Comment by angelo234** [comment]
Hey, did you get my email of what it looked like on my end when I imported it?

**Comment by AlexEL204** [comment]
Yes, and it has only imported the hitboxes

**Comment by angelo234** [comment]
What do you mean by hitboxes? Try to uninstall the current plugin and install the new plugin again and see if that fixes it.

**Comment by AlexEL204** [comment]
> What do you mean by hitboxes?

I mean by these low poly models that somewhat resemble the object it's associated with.

**Comment by AlexEL204** [comment]
> Try to uninstall the current plugin and install the new plugin again and see if that fixes it.

It did not

**Comment by angelo234** [comment]
Can you send me a screenshot of this "hitbox"

**Comment by AlexEL204** [comment]
![Captura de tela 2024-09-24 231419](https://github.com/user-attachments/assets/e1227034-b300-434c-a413-1d14f05366c4)

**Comment by angelo234** [comment]
Thats what I got like I sent you before, its normal, those "hitboxes" I'm guessing you are referring to are the triangles/quads. I'm not sure what the issue is?

**Comment by AlexEL204** [comment]
But do you know how I can get the actual geometry of the game objects?

**Comment by angelo234** [comment]
What you see is the representation of the JBeam structure. The vertices of the mesh are the nodes, the edges are the beams, the faces are the triangles/quads. Not sure if that answers your question?

**Comment by AlexEL204** [comment]
But how do I get the high poly mesh that is used as the visual portrayal of BeamNG's objects??

**Comment by angelo234** [comment]
This plugin doesn't import the dae mesh, you can import the dae mesh yourself.

**Comment by AlexEL204** [comment]
Thank you, that's what I wanted to know the entire time!! kthxbai.
