### ISSUE TITLE
No jbeams are shown

### ISSUE THREAD

**Issue by SKYMEE1** [BeamNG/Blender-JBeam-Editor#3]
When I create the jbeam nothing happens. With release 1.0 the jbeams show up. After 1.0 they won't show up.

**Comment by angelo234** [comment]
Sorry, I'm not sure what you are trying to say. Could you post a video or something of what the issue is, thanks.

**Comment by SKYMEE1** [comment]
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/47692494/aafa8172-e652-4b75-ae2f-1883e03cb549)
As you can see, I can not select any jbeam because they don't even show up.

**Comment by angelo234** [comment]
Hmm, I get this issue when I save the blender project and reopen it. Is this the steps you did too?

**Comment by angelo234** [comment]
I'm gonna release a new version for now that I think fixes this bug. If you still find this bug, please let me know :)
