### ISSUE TITLE
editor doesnt save jbeam

### ISSUE THREAD

**Issue by johnnnnnnnnnnnnnny** [BeamNG/Blender-JBeam-Editor#30]
just changed the location of the nodes of the jbeam and when exporting it says its successful but when importing the same jbeam its back in the original places

**Comment by angelo234** [comment]
Did you import a .pc file or a .jbeam file? Could you show me the logs (Window > Toggle system console)?

**Comment by johnnnnnnnnnnnnnny** [comment]
it was a jbeam file

![image](https://github.com/user-attachments/assets/daed73a8-d8ed-4cb8-b42d-db443a44f5de)

![image](https://github.com/user-attachments/assets/af6f7060-a35c-4ed8-ac71-9936057d0d98)

**Comment by angelo234** [comment]
Could you send me the JBeam file to amatteo@beamng.com

**Comment by angelo234** [comment]
Hmm it worked for me. Could you uninstall the plugin and reinstall it. Maybe the installed plugin is glitched.

**Comment by johnnnnnnnnnnnnnny** [comment]
idk what it is i reinstalled it and its still not working maybe i not doing something right

**Comment by angelo234** [comment]
Try uninstalling the plugin, restart Blender, and then install the plugin and restart and try importing the JBeam file.

**Comment by johnnnnnnnnnnnnnny** [comment]
i did and still doesnt save. when moving the node the numbers change but when exporting then importing it reverts

![image](https://github.com/user-attachments/assets/789ab0ef-3a06-4b11-a7eb-98ea2239a9e0)
![image](https://github.com/user-attachments/assets/ad15d525-9205-4839-9ecb-2129d98639f4)
![image](https://github.com/user-attachments/assets/25ec4f68-2fd8-47e8-81dc-892c11d1f780)

**Comment by angelo234** [comment]
Oh you need to select the part and then click on "Selected JBeam Part(s)", which comes from this plugin.

**Comment by angelo234** [comment]
That other option I think is from some other plugin.

**Comment by johnnnnnnnnnnnnnny** [comment]
ahh okay it worked thanks
