### ISSUE TITLE
Created Jbeam mesh in blender file is not showing node ids and crashes blender when attempting to enter edit mode

### ISSUE THREAD

**Issue by Place-h0lder** [BeamNG/Blender-JBeam-Editor#6]
Pretty much exactly what the title says, no node ids, and when I press tab Blender closes. I made a mesh for a vehicle mod I was wanting to make (first mod, yay) and the node ids disappeared after reloading the file, and now I cant edit the mesh for the jbeam, and I can't import exported versions of the mesh, because they have the very same problem as the mesh in the original file. I honestly don't know what I messed up, but clearly something has happened. no hurry for a response, I still have some 3d modeling to do, and i have work tomorrow, just wanted to post this before bed. Appreciate your time.

**Comment by angelo234** [comment]
Hmm, what version of Blender are you using? It seems to work for me on Blender 3.6.4

**Comment by angelo234** [comment]
Closed due to inactivity
