### ISSUE TITLE
Not able to export jbeam / Option greyed out

### ISSUE THREAD

**Issue by O1LER** [BeamNG/Blender-JBeam-Editor#8]
Blender 3.6.5
Jbeam tool 0.1.4

Im unable to export a jbeam file, since the option for that is greyed out

![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/44237025/a8287079-0937-423b-8f1c-33cdbb6788af)

It used to work fine a month ago with version 0.1.0
Tried reinstalling the plugin, as well as blender, no change

**Comment by O1LER** [comment]
I seem to have found the issue

If the meshes are only marked on the scene tree, then the export is not possible
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/44237025/7ce8a3a9-bb85-4828-9eed-7140f131714f)

If at least one of them is actually selected, then the export is possible
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/44237025/f31583a9-7353-469c-a588-830c1c15018d)

Entirely possible that this is intended behavior though

**Comment by angelo234** [comment]
Hmm I guess I could make it so selecting it in the scene tree could allow you to export.

**Comment by angelo234** [comment]
You can now select parts to export with the scene tree
