### ISSUE TITLE
Error: object_begin or list_begin w/o key!

### ISSUE THREAD

**Issue by MrTheRich** [BeamNG/Blender-JBeam-Editor#9]
I'm getting this error in the python console, upon importing and directly exporting a valid jbeam file.

Looking in the code the error seems to be triggered because the global dictionary of the file doesn't have a key obviously. But the code doesn't seem to differentiate between that.

![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/8750575/3d061543-00d3-4d61-9f6d-e689da3bfa1a)
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/8750575/a0a6b20d-4ea2-41e5-914a-a10c6f1fad03)

**Comment by angelo234** [comment]
Yeah so that "error" isn't an error, but only for the global dictionary 👍
